language: python
services:
    - docker
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python test.py
before_deploy:
    - docker build -t jmorganwalker/flask:$TRAVIS_TAG .
deploy:
    provider: script
    script: deploy.sh
    on:
        tags: true