language: python
services:
    - docker
python:
  - "2.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python test.py
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push jmorganwalker/flask;
    fi
