language: python
services:
  - docker
install:
  - docker build -t flask .
  - docker run -p 8000:8000 --name flask1 -d flask
script:
  - docker ps | grep -q flask
  - docker exec -it flask1 python /deploy/app/test.py
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $DOCKER_REPOSITORY;
    fi
  - curl -X POST -d "" $CLOUD66_PRODUCTION_REDEPLOYMENT_URL
