apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-service
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    run: flask-service
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: flask-deployment
    spec:
      containers:
      - name: flask-deployment
        image: jmorganwalker/simple-python-http
        ports:
        - containerPort: 8000